// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5rxAYAxFSKklE_4H1oCRX2kUE-nnWvQM',
    appId: '1:814269916408:web:9e9dfdc6fd7d792265470d',
    messagingSenderId: '814269916408',
    projectId: 'crud-6f53d',
    authDomain: 'crud-6f53d.firebaseapp.com',
    storageBucket: 'crud-6f53d.firebasestorage.app',
    measurementId: 'G-RP1GCXSY7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB37f6z51BdPUNKyr6OzZ9Mh8aY0trwBqM',
    appId: '1:814269916408:android:4cd4911ba106374565470d',
    messagingSenderId: '814269916408',
    projectId: 'crud-6f53d',
    storageBucket: 'crud-6f53d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7A9Ps5WWe00NDPHEryELvzt6A_zlkyOo',
    appId: '1:814269916408:ios:08186773bbc1006e65470d',
    messagingSenderId: '814269916408',
    projectId: 'crud-6f53d',
    storageBucket: 'crud-6f53d.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5rxAYAxFSKklE_4H1oCRX2kUE-nnWvQM',
    appId: '1:814269916408:web:6ec7da5095e3759d65470d',
    messagingSenderId: '814269916408',
    projectId: 'crud-6f53d',
    authDomain: 'crud-6f53d.firebaseapp.com',
    storageBucket: 'crud-6f53d.firebasestorage.app',
    measurementId: 'G-3QNWS5H4B1',
  );
}
